alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
alter table address drop constraint FKg6qcywqtp08ksr5r9lpv16g1k
alter table configuracao drop constraint fk_configuracao_usuario
alter table email_entity drop constraint FKdjnij1xj64twxe7nle3erjn9h
alter table phone drop constraint FK3wql5uvlg7a9y93qpgccvh9oj
alter table student_address drop constraint FKri7u57cq6xu0spcc1aii9prvw
alter table student_address drop constraint FK10mpuj1mmky2gmxxtxt0sbqdr
alter table student_phone drop constraint FK660eaucw2dd4d21bkusnlrtyl
alter table student_phone drop constraint FKcmaqce3eg166eeer7wk90fmy1
alter table userconfiguration drop constraint FKjqk18j3pigibdbeaslwli4jvc
alter table users_profile drop constraint FKori9a2k03im1lb5c71jb0jjw7
alter table users_profile drop constraint FKfc2ktn0dd34entljh9t4sirwx
alter table usuario drop constraint fk_usuario_dominio
alter table usuario_grupo drop constraint fk_usuario_grupo_grupo
alter table usuario_grupo drop constraint fk_usuario_grupo_usuario
drop table if exists address cascade
drop table if exists client cascade
drop table if exists configuracao cascade
drop table if exists dominio cascade
drop table if exists email_entity cascade
drop table if exists grupo cascade
drop table if exists phone cascade
drop table if exists profile cascade
drop table if exists student cascade
drop table if exists student_address cascade
drop table if exists student_phone cascade
drop table if exists tb_payment cascade
drop table if exists tb_product cascade
drop table if exists tb_user cascade
drop table if exists temporal_values cascade
drop table if exists userconfiguration cascade
drop table if exists users cascade
drop table if exists users_phone cascade
drop table if exists users_profile cascade
drop table if exists usuario cascade
drop table if exists usuario_grupo cascade
drop sequence if exists custom_sequence
